name             'create'
maintainer       'Garry Cyre'
maintainer_email 'gcyre@kobo.com'
license          'All rights reserved'
description      'Installs/Configures create'
long_description 'Installs/Configures create'
version          '0.1.0'
